# Название рабочего процесса
name: Go

# Условие запуска
on:
  # Запуск по событию "push" (заливка изменений в ветку)
  push:
    # Указывает, что нужно запускать рабочий процесс, только если событие относится к ветке main
    branches: [ "main" ]
  # Запуск по событию "pull_request". Поле "types" не указано, поэтому учитываются события по открытию, переоткрытию пул-реквеста и изменению в ветке.
  pull_request:
    # Указывает, что нужно запускать рабочий процесс, только если событие относится к ветке main
    branches: [ "main" ]

# Задания
jobs:
  # Задание с идентификатором "build"
  build:
    # Для запуска задания используется раннер "ubuntu-latest", что соответствует последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги задания
    steps:
    # Первый шаг использует действие "actions/checkout@v3", которое извлекает репозиторий для дальнейшей работы с ним
    - uses: actions/checkout@v3

    # Шаг с именем "Set up Go"
    - name: Set up Go
      # Этот шаг использует действие "actions/setup-go@v4", которое установит Go в систему
      uses: actions/setup-go@v4
      # Для этого действия можно задать версию Go, которую надо установить
      with:
        go-version: '1.21'

    - name: Set up SQLite       
      run: go mod download

    # Шаг с именем "Build"
    - name: Build      
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v ./.

    # Шаг с именем "Test"
    - name: Test      
      run: go test -v ./.